version: '3.8'

services:
  openproject:
    image: openproject/openproject:16
    container_name: openproject
    ports:
      - "8080:80"
    environment:
      OPENPROJECT_SECRET_KEY_BASE: supersecret123
      OPENPROJECT_HOST__NAME: localhost:8080
      OPENPROJECT_HTTPS: "false"
      OPENPROJECT_DEFAULT__LANGUAGE: es
    volumes:
      - ./pgdata:/var/openproject/pgdata
      - ./assets:/var/openproject/assets
    restart: always
